# Generated by Django 2.2.2 on 2019-06-04 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pmo2015.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('gen_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('taobao_id', models.CharField(max_length=16)),
                ('status', models.SmallIntegerField(default=0)),
                ('signup_time', models.DateTimeField(auto_now=True)),
                ('signup_ip', models.GenericIPAddressField()),
                ('team', models.CharField(choices=[('AQ', '水舰队'), ('MG', '熔岩团')], help_text='所属队伍', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('gen_time', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('AQ', '水舰队'), ('MG', '熔岩团')], help_text='选择', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PmoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('pmo', models.CharField(choices=[('unknown', 'unknown'), ('pmo2015', 'pmo2015'), ('pmo2016', 'pmo2016'), ('pmo2017', 'pmo2017'), ('pmo2018', 'pmo2018'), ('pmo2019', 'pmo2019')], default='unknown', help_text='漫展', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('gen_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(default=pmo2015.models.user.PmoAdmin.get_default_admin, on_delete=django.db.models.deletion.CASCADE, to='pmo2015.PmoAdmin')),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='BackComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('gen_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmo2015.PmoAdmin')),
                ('toward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo2015.MainComment')),
            ],
        ),
    ]
