# Generated by Django 2.2.2 on 2019-06-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pmo',
            field=models.CharField(choices=[('unknown', 'unknown'), ('pmo2017', 'pmo2017'), ('pmo2015', 'pmo2015'), ('pmo2016', 'pmo2016'), ('pmo2018', 'pmo2018'), ('pmo2019', 'pmo2019')], default='unknown', help_text='漫展', max_length=10),
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='pmo',
            field=models.CharField(choices=[('unknown', 'unknown'), ('pmo2017', 'pmo2017'), ('pmo2015', 'pmo2015'), ('pmo2016', 'pmo2016'), ('pmo2018', 'pmo2018'), ('pmo2019', 'pmo2019')], default='unknown', help_text='漫展', max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pmo',
            field=models.CharField(choices=[('unknown', 'unknown'), ('pmo2017', 'pmo2017'), ('pmo2015', 'pmo2015'), ('pmo2016', 'pmo2016'), ('pmo2018', 'pmo2018'), ('pmo2019', 'pmo2019')], default='unknown', help_text='漫展', max_length=10),
        ),
        migrations.AlterField(
            model_name='validatecode',
            name='pmo',
            field=models.CharField(choices=[('unknown', 'unknown'), ('pmo2017', 'pmo2017'), ('pmo2015', 'pmo2015'), ('pmo2016', 'pmo2016'), ('pmo2018', 'pmo2018'), ('pmo2019', 'pmo2019')], default='unknown', help_text='漫展', max_length=10),
        ),
    ]
