# Generated by Django 2.2.2 on 2019-06-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmo2015', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('gen_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('taobao_id', models.CharField(max_length=16)),
                ('status', models.SmallIntegerField(default=0)),
                ('signup_time', models.DateTimeField(auto_now=True)),
                ('signup_ip', models.GenericIPAddressField()),
                ('phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BackComment2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('gen_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmo2015.PmoAdmin')),
                ('toward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmo2016.MainComment')),
            ],
        ),
    ]
